{{- if and .Values.git.token (not .Values.git.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agrelha.fullname" . }}-git
  labels: {{- include "agrelha.labels" . | nindent 4 }}
type: Opaque
stringData:
  GIT_USERNAME: {{ .Values.git.username | quote }}
  GIT_TOKEN: {{ .Values.git.token | quote }}
{{- end }}
{{- if and .Values.oidc.enabled .Values.oidc.clientSecret (not .Values.oidc.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agrelha.fullname" . }}-oidc
  labels: {{- include "agrelha.labels" . | nindent 4 }}
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | quote }}
{{- end }}
