[tools]
"aqua:go-task/task" = "latest"
go = "1.26.7"
"go:github.com/a-h/templ/cmd/templ" = "latest"
"go:github.com/air-verse/air" = "latest"
bun = "latest"

[settings]
experimental = true # required for the golang-backend tool installs
